fpm:
  image: dmoraschi/centos-phpcphalcon
  restart: always
  volumes:
    - "./:/data"

nginx:
  image: dmoraschi/centos-nginx
  restart: always
  volumes_from:
    - fpm
  volumes:
    - ./nginx/:/etc/nginx/conf.d/:ro
  links:
    - fpm

haproxy:
  image: haproxy:1.5
  restart: always
  ports:
    - "8080:80"
  links:
    - nginx
  volumes:
    - ./haproxy/:/usr/local/etc/haproxy/:ro
